"""empty message

Revision ID: 0f5952acb183
Revises: 6cdac573f30b
Create Date: 2018-01-29 22:36:45.964236

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0f5952acb183'
down_revision = '6cdac573f30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('door',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('door_status', sa.Boolean(), nullable=True),
    sa.Column('door_motion', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_door'))
    )
    with op.batch_alter_table('door', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_door_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_door_date'))

    op.drop_table('door')
    # ### end Alembic commands ###
