"""empty message

Revision ID: 6cdac573f30b
Revises: e5b84add53cd
Create Date: 2018-01-18 23:15:52.469557

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '6cdac573f30b'
down_revision = '69af592a203a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door', schema=None) as batch_op:
        batch_op.drop_constraint('uq_door_door_motion', type_='unique')
        batch_op.drop_constraint('uq_door_door_status', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_door_door_status', ['door_status'])
        batch_op.create_unique_constraint('uq_door_door_motion', ['door_motion'])

    # ### end Alembic commands ###
